import mockProductImage from '../../assets/mockProductImage.png';
import moment, { Moment } from 'moment';

const data: {
  issueDate: Moment;
  productCategory: string;
	productID: number;
  productImage: string;
	productName: string;
  referencePrice: number;

}[] = [
	{
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 1,
    productImage: mockProductImage,
		productName: 'Product A',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 2,
    productImage: mockProductImage,
		productName: 'Product B',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 3,
    productImage: mockProductImage,
		productName: 'Product C',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 4,
    productImage: mockProductImage,
		productName: 'Product D',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 5,
    productImage: mockProductImage,
		productName: 'Product E',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 6,
    productImage: mockProductImage,
		productName: 'Product F',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 7,
    productImage: mockProductImage,
		productName: 'Product G',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 8,
    productImage: mockProductImage,
		productName: 'Product H',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 9,
    productImage: mockProductImage,
		productName: 'Product I',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 10,
    productImage: mockProductImage,
		productName: 'Product J',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 11,
    productImage: mockProductImage,
		productName: 'Product K',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 12,
    productImage: mockProductImage,
		productName: 'Product L',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 13,
    productImage: mockProductImage,
		productName: 'Product M',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 14,
    productImage: mockProductImage,
		productName: 'Product N',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 15,
    productImage: mockProductImage,
		productName: 'Product O',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 16,
    productImage: mockProductImage,
		productName: 'Product P',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 17,
    productImage: mockProductImage,
		productName: 'Product Q',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 18,
    productImage: mockProductImage,
		productName: 'Product R',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 19,
    productImage: mockProductImage,
		productName: 'Product S',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 20,
    productImage: mockProductImage,
		productName: 'Product T',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 21,
    productImage: mockProductImage,
		productName: 'Product U',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 22,
    productImage: mockProductImage,
		productName: 'Product V',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 23,
    productImage: mockProductImage,
		productName: 'Product W',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 24,
    productImage: mockProductImage,
		productName: 'Product X',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 25,
    productImage: mockProductImage,
		productName: 'Product Y',
    referencePrice: 10,
	},
  {
    issueDate: moment('2023-01-01'),
    productCategory: 'Product Category 1',
		productID: 26,
    productImage: mockProductImage,
		productName: 'Product Z',
    referencePrice: 10,
	},
];
export default data;